In [2]:
print("Hello ")

Hello

In [3]:
a=10
print(a)

10

In [4]:
a=100
print(type(a))

<class 'int'>

In [10]:
x=int(input("Enter the value"))
print(type(x))

Enter the value 10

<class 'int'>

num_str="10"
print(type(num_str))
num_int=int(num_str)
print(type(num_int))

In [22]:
name="RAMA Seetha"
print(name[:])

RAMA Seetha

In [23]:
name1='Rama'
name2='Seetha'
print(name1+name2)

RamaSeetha

In [25]:
a=int(input("Enter the value of a"))
b=int(input("Enter the value of b"))
print(a+b)

Enter the value of a 10
Enter the value of b 20

30

In [26]:
sentence = "  The quick brown fox jumps over the lazy dog. The dog is not so lazy after all!"
print(sentence)

#Task1 Convert the sentence to lowercase
lower_case=sentence.lower()
print(lower_case)

#Task2 Convert the sentence to Uppercase
upper_case=sentence.upper()
print(upper_case)

# Task3 Remove any leading or trailing whitespace.
Space=sentence.strip()
print(Space)


# Task4 Replace a given word with another word.(Cat)
replaced_sentence = sentence.replace("dog", "cat")
print(replaced_sentence)

# Task5 Count 
count=sentence.count("dog")
print(count)

# Task6 Capitalize the first letter of each word in the sentence.
Title=sentence.title()
print(Title)

  The quick brown fox jumps over the lazy dog. The dog is not so lazy after all!
  the quick brown fox jumps over the lazy dog. the dog is not so lazy after all!

In [1]:
#Write a python program to all Arithmetic Operations

# Taking input from user
a=float(input("Enter the Value of a"))
b=float(input("Enter the Value of b"))

# Performing operations
print("\nResults:")
print("Addition:", a+b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)
print("Floor Division:", a // b)

Enter the Value of a 10
Enter the Value of b 20

Results:
Addition: 30.0
Subtraction: -10.0
Multiplication: 200.0
Division: 0.5
Floor Division: 0.0

In [5]:
# Logical Operators Example
a = True
b = False
print("a =", a)
print("b =", b)
# AND operator
print("a and b:", a and b)
# OR operator
print("a or b:", a or b)
# NOT operator
print("not a:", not a)

a = True
b = False
a and b: False
a or b: True
not a: False

In [8]:
# Write a pyhton program to find given value is Positive or Nagitive.
num1=int(input("Enter the number: "))

if num1>0:
    print(num1,"+ve")
elif num1<0:
    print(num1,"-ve")
else: 
    print("num is Zero: ")

Enter the number:  -1

-1 -ve

In [ ]:
#Write a py program to find given number is Even or Odd number.
n=int(input("Enter the num: "))
if n==0:
    print("number is Zero")
elif n%2==0:
    print("given number is Even")
else: 
    print("geven number is Odd")

In [10]:
#Write a py program to find given number is Even or Odd number.
n=int(input("Enter the num: "))
if n==0:
    print("number is Zero")
elif n%2==0:
    print("given number is Even")
else: 
    print("geven number is Odd")

Enter the num:  0

number is Zero

In [14]:
balance = 10000  

withdraw_amount = int(input("Enter amount to withdraw: "))

if withdraw_amount <= 0:
    print("Invalid amount")

elif withdraw_amount > balance:
    print("Insufficient balance")

else:
    balance = balance - withdraw_amount
    print("Please collect your cash")
    print("Remaining balance:", balance)

Enter amount to withdraw:  5

Please collect your cash
Remaining balance: 9995

In [15]:
'''
#Syntax for looping
for variable in sequence:
    # code block
'''
for a in range(1,6):
    print("Hello--->",a)

Hello---> 1
Hello---> 2
Hello---> 3
Hello---> 4
Hello---> 5

In [16]:
fruits=["Apple","Orange","Mango","Banana"]
for i in fruits:
    print(i)

Apple
Orange
Mango
Banana

In [ ]:
students = ["Krishna", "Dhiraj", "Satish", "Ganesh","Vinay"]

for name in students:
    print(name, "is present")

In [17]:
tasks = ["Wake up", "Exercise", "Study", "Sleep"]

for task in tasks:
    print("Don’t forget to:", task)

Don’t forget to: Wake up
Don’t forget to: Exercise
Don’t forget to: Study
Don’t forget to: Sleep

In [20]:
'''
Question
Write a Python program to display the names of items in a shopping cart.
The cart contains items: ["Milk", "Bread", "Rice", "Eggs"].
Use a for loop to print each item with a message.
'''    

# Shopping cart items:
items=["Milk","Bread","Rice","Eggs"]

for i in items:
    print("Item in cart:", i)

Item in cart: Milk
Item in cart: Bread
Item in cart: Rice
Item in cart: Eggs

In [27]:
# Write a python program to print Multiplication table
num= int(input("Enter the num"))

for i in range(1,11):
    print(num,'x',i,'=',i*num)

Enter the num 10

10 x 1 = 10
10 x 2 = 20
10 x 3 = 30
10 x 4 = 40
10 x 5 = 50
10 x 6 = 60
10 x 7 = 70
10 x 8 = 80
10 x 9 = 90
10 x 10 = 100

In [28]:
'''
#Syntax for while loop 
while condition:
    # code to repeat
'''

i = 1
while i <= 5:
    print(i)
    i += 1

1
2
3
4
5

In [29]:
 
water_level = 0
tank_capacity = 100

while water_level < tank_capacity:
    print("Filling water... Current level:", water_level)
    water_level += 20
    
print("Tank is full")

Filling water... Current level: 0
Filling water... Current level: 20
Filling water... Current level: 40
Filling water... Current level: 60
Filling water... Current level: 80
Tank is full

In [32]:
#List and methods 
#append()
fruits = ["apple", "banana"]
fruits.append("cherry")
print(fruits)

#insert()
fruits = ["apple", "banana"]
fruits.insert(0, "orange")
print(fruits)

#extend()
fruits = ["apple", "banana"]
fruits.extend(["cherry", "grape"])
print(fruits)

['apple', 'banana', 'cherry']
['orange', 'apple', 'banana']
['apple', 'banana', 'cherry', 'grape']

In [33]:
#remove()
fruits = ["apple", "banana", "cherry", "banana"]
fruits.remove("banana")
print(fruits)

['apple', 'cherry', 'banana']

In [34]:
#pop()
fruits = ["apple", "banana", "cherry"]
fruits.pop(1)
print(fruits)

['apple', 'cherry']

In [ ]:
#Clear()
fruits = ["apple", "banana", "cherry"]
fruits.clear()
print(fruits)

In [ ]:
#sort()
nums = [3, 1, 4, 2]
nums.sort()
print(nums)

In [35]:
#index()
fruits = ["apple", "banana", "cherry"]
print(fruits.index("banana"))

1

In [36]:
#count()
nums = [1, 2, 2, 3, 2]
print(nums.count(2))

3

In [37]:
'''
Create a list of fruits.
Add "mango" at the end.
Insert "orange" at index 1.
Print the final list.
'''

# Initial fruit list
fruits = ["apple", "banana", "cherry"]

# Add "mango" at the end
fruits.append("mango")

# Insert "orange" at index 1
fruits.insert(1, "orange")

# Print the final list
print("Final Fruit List:", fruits)

Final Fruit List: ['apple', 'orange', 'banana', 'cherry', 'mango']

In [ ]:
'''
Question:
You are going shopping.
Start with a list: ["milk", "bread", "eggs"]
Add "butter" and "jam" to the list
Remove "bread" from the list
Sort the items alphabetically
Print the final shopping list
'''
# Initial grocery list
grocery = ["milk", "bread", "eggs"]

# Add butter and jam
grocery.append("butter")
grocery.append("jam")

# Remove bread
grocery.remove("bread")

# Sort alphabetically
grocery.sort()

# Print final list
print("Final Shopping List:", grocery)

In [40]:
Demo=(10,20,30)

Demo[1]=100
print(Demo)

TypeError: 'tuple' object does not support item assignment

In [39]:
demo=[1,2,3]
print(type(demo))

<class 'list'>

In [43]:
i=1
while i<20:
    i*=2
print(i)

32

# Set Examples

In [2]:
#Sets Examples 
# Creating a set
fruits = {"apple", "banana", "cherry"}

# Adding elements to a set
fruits.add("mango")
fruits.add("apple")  
print(fruits)

{'apple', 'mango', 'cherry', 'banana'}

In [ ]:
#Set Methods
#add()
fruits = {"apple", "banana"}
fruits.add("cherry")
print(fruits)

In [ ]:
#Update
fruits = {"apple", "banana"}
fruits.update(["cherry", "grape"])
print(fruits)

In [ ]:
#Remove
fruits = {"apple", "banana", "cherry"}
fruits.remove("banana")
print(fruits)

In [3]:
#Union
a = {1, 2, 3}
b = {3, 4, 5}
print(a.union(b))

{1, 2, 3, 4, 5}

In [4]:
#intersection
a = {1, 2, 3}
b = {2, 3, 4}
print(a.intersection(b))

{2, 3}

In [5]:
#diffrence()
a = {1, 2, 3}
b = {2, 3, 4}
print(a.difference(b))

{1}

In [6]:
'''
Two different courses have student lists:
Python class: {"Ravi", "Anita", "Kiran", "Rahul"}
Java class: {"Kiran", "Rahul", "Sneha", "Meena"}

👉 Write a Python program to:
Find students who are learning both Python and Java.
Find students who are learning only Python.
Find students who are learning only Java.
Find all unique students from both classes.
'''

# Student sets
python_class = {"Ravi", "Anita", "Kiran", "Rahul"}
java_class = {"Kiran", "Rahul", "Sneha", "Meena"}



# 1. Students learning both Python and Java
both = python_class.intersection(java_class)

# 2. Students learning only Python
only_python = python_class.difference(java_class)

# 3. Students learning only Java
only_java = java_class.difference(python_class)

# 4. All unique students
all_students = python_class.union(java_class)

# Print results
print("Both Python & Java:", both)
print("Only Python:", only_python)
print("Only Java:", only_java)
print("All Students:", all_students)

Both Python & Java: {'Kiran', 'Rahul'}
Only Python: {'Anita', 'Ravi'}
Only Java: {'Sneha', 'Meena'}
All Students: {'Sneha', 'Meena', 'Kiran', 'Anita', 'Rahul', 'Ravi'}

In [8]:
'''
You and your friend went shopping.
Your list: {"milk", "bread", "eggs", "butter"}
Friend's list: {"bread", "butter", "jam", "cheese"}
👉 Write a Python program to find:
Items both of you bought
Items only you bought
Items only your friend bought
The list of all unique items
'''

# Shopping lists
my_list = {"milk", "bread", "eggs", "butter"}
friend_list = {"bread", "butter", "jam", "cheese"}

# 1. Items both bought
both = my_list.intersection(friend_list)

# 2. Items only I bought
only_me = my_list.difference(friend_list)

# 3. Items only friend bought
only_friend = friend_list.difference(my_list)

# 4. All unique items
all_items = my_list.union(friend_list)

# Print results
print("Both Bought:", both)
print("Only I Bought:", only_me)
print("Only Friend Bought:", only_friend)
print("All Items:", all_items)

Both Bought: {'butter', 'bread'}
Only I Bought: {'eggs', 'milk'}
Only Friend Bought: {'jam', 'cheese'}
All Items: {'butter', 'cheese', 'eggs', 'jam', 'milk', 'bread'}

In [7]:
#example for  Set Union (|) 
coding = {"Amit", "Riya", "John", "Sneha"}
design = {"Sneha", "Rahul", "John", "Priya"}

all_students = coding | design

print("Total Participants:")
print(all_students)

Total Participants:
{'Sneha', 'Amit', 'Priya', 'John', 'Rahul', 'Riya'}

In [ ]:
#Example for Set Intersection (&)
team_a = {"Virat", "Rohit", "Gill", "Rahul"}
team_b = {"Gill", "Rahul", "Hardik", "Jadeja"}

common_players = team_a & team_b

print("Players in Both Teams:")
print(common_players)

In [ ]:
#Example for Set Difference (-)
coding = {"Prajwal", "Mandar", "Rahul Patil ", "Soundarya"}
design = {"Soundarya", "Akash Magadum ", "Rahul Patil", "Priya"}

only_coding = coding - design

print("Only Coding Students:")
print(only_coding)

# Dictionaries Examples

In [13]:
# Creating a dictionary 
student = {
"name": "John", 
"age": 25, 
"country": "USA"} 

print(type(student))
print(student)

<class 'dict'>
{'name': 'John', 'age': 25, 'country': 'USA'}

In [14]:
#clear()
student = {"name": "John", "age": 20, "county":"USA"}
student.clear()
print(student)

{}

In [15]:
#copy()
student = {"name": "Arvind", "age": 20}
new_student = student.copy()
print(new_student) 
print(type(new_student))

{'name': 'Arvind', 'age': 20}
<class 'dict'>

In [17]:
#get method 
student = {"name": "Ravi", "age": 20}
print(student.get("age"))        
print(student.get("course", "xyz"))

20
xyz

In [18]:

#items()
student = {"name": "Ravi", "age": 20}
print(student.items())

dict_items([('name', 'Ravi'), ('age', 20)])

In [19]:

#Keys()
student = {"name": "Ravi", "age": 20}
print(student.keys())

dict_keys(['name', 'age'])

In [20]:

'''
Create a dictionary of 3 subjects and marks. 
Example:
marks = {"Math": 90, "Science": 85, "English": 88}
# Print items
# Remove last inserted
'''
marks = {"Math": 90, "Science": 85, "English": 88}

# Print items
print("Subjects with marks:", marks.items())

# Remove last inserted
marks.popitem()

print("After popitem:", marks)

Subjects with marks: dict_items([('Math', 90), ('Science', 85), ('English', 88)])
After popitem: {'Math': 90, 'Science': 85}

In [23]:
'''
Create a dictionary where product names are keys and prices are values.

1.Use get() to print the price of a product entered by the user.
2.Add a new product using setdefault().
3.Remove the last inserted product using popitem().
4.Show all items using items().
''' 

# Shopping Cart Dictionary
cart = {"Pen": 10,"Book": 120,"Pencil": 5,"Bag": 450 }
# 1. Get the price of a product
product = "Book"
print("Price of", product, "is:", cart.get(product, "Not Found"))

# 2. Add a new product using setdefault()
cart.setdefault("Eraser", 15)

# 3. Remove the last inserted product
removed_item = cart.popitem()
print("Removed:", removed_item)

# 4. Show all items
print("Available products:")
for i, p in cart.items():
    print(i, ":", p)

Price of Book is: 120
Removed: ('Eraser', 15)
Available products:
Pen : 10
Book : 120
Pencil : 5
Bag : 450

# Fuction Examples

In [29]:
#Example for functions
print("Hi")
def greet():
    print("Hello, welcome to Python!")
print("Bye")
greet()

Hi
Hello, welcome to Python!
Bye

In [30]:
#Example for function with parameter 
def Arth(a,b):
    c=a+b
    print(c)

Arth(1,2)

3

In [31]:
#function with return type
def add(a, b):
    return a + b

a=int(input("Enter the value of a: "))
b=int(input("Enter the value of b: "))
result = add(a, b)
print("Sum:", result)

Enter the value of a:  10
Enter the value of b:  20

Sum: 30

In [32]:
# Function for addition
def add(a, b):
    return a + b

# Function for subtraction
def subtract(a, b):
    return a - b

# Function for multiplication
def multiply(a, b):
    return a * b

# Function for division
def divide(a, b):
    if b != 0:
        return a / b
    else:
        return "Cannot divide by zero"

# Example usage
print("Addition:", add(10, 5))
print("Subtraction:", subtract(10, 5))
print("Multiplication:", multiply(10, 5))
print("Division:", divide(10, 0))

Addition: 15
Subtraction: 5
Multiplication: 50
Division: Cannot divide by zero

In [ ]:
def calculate_bill(price, quantity):
    total = price * quantity
    return total

item1 = calculate_bill(50, 3)   
item2 = calculate_bill(20, 5)   

print("Item 1 Bill:", item1)
print("Item 2 Bill:", item2)

# Examples for moduls

In [33]:
import time

current_time = time.time()
print("Current Time:", current_time)

Current Time: 1782551631.1055913

In [34]:
import time

current_time = time.ctime()
print("Current Time:", current_time)

Current Time: Sat Jun 27 14:46:58 2026

In [35]:
import time

print("Hello")
time.sleep(7)   
print("Welcome after 7 seconds!")

Hello
Welcome after 7 seconds!

In [36]:
import time

current_time = time.localtime()

print("Full Date & Time:", time.strftime("%Y-%m-%d %H:%M:%S", current_time))
print("Only Date:", time.strftime("%d/%m/%Y", current_time))
print("Only Time:", time.strftime("%I:%M %p", current_time))
print("Day Name:", time.strftime("%A", current_time))

Full Date & Time: 2026-06-27 15:01:55
Only Date: 27/06/2026
Only Time: 03:01 PM
Day Name: Saturday

In [52]:
import random
print(random.random())

0.6367685940351305

In [67]:
import random
print(random.randint(1,7))

5

In [90]:
#real time example 
import random

print("Rolling the dice...")
dice = random.randint(1, 6)
print("You got:", dice)

Rolling the dice...
You got: 1

In [117]:
import random
fruits = ["apple", "banana", "cherry", "mango"]
print(random.choice(fruits))

mango

In [122]:
import random

participants = ["Rahul", "Iranna Hosur ", "Aditya Desai", "Ali Kazi ", "Omkar"]

# shuffle the list
random.shuffle(participants)

# first person becomes the winner
winner = participants[0]

print("Participants:", participants)
print("Lucky Draw Winner is:", winner)

Participants: ['Omkar', 'Aditya Desai', 'Rahul', 'Iranna Hosur ', 'Ali Kazi ']
Lucky Draw Winner is: Omkar

# Math Module Example

In [124]:
import math

print("=" * 50)
print("       PYTHON MATH MODULE METHODS")
print("=" * 50)

print("\n1. Constants")
print("Value of PI =", math.pi)
print("Value of e =", math.e)

# -----------------------------
# Logarithmic Functions
# -----------------------------
print("\n2. Logarithmic Functions")
num = 100
print("Natural Log of", num, "=", math.log(num))
print("Base-10 Log of", num, "=", math.log10(num))

# -----------------------------
# Exponential Function
# -----------------------------
print("\n3. Exponential Function")

print("exp(2) =", math.exp(2))

# -----------------------------
# Power Function
# -----------------------------
print("\n4. Power Function")

print("2 raised to the power 5 =", math.pow(2, 5))
print("5 raised to the power 3 =", math.pow(5, 3))

# -----------------------------
# Rounding Functions
# -----------------------------
print("\n5. Rounding Functions")

number = 8.65

print("Original Number =", number)
print("Ceiling =", math.ceil(number))
print("Floor =", math.floor(number))
print("Round =", round(number))

number2 = 8.5
print("\nRound(8.5) =", round(number2))

number3 = 9.5
print("Round(9.5) =", round(number3))

print("\n" + "=" * 50)
print("Program Completed Successfully")
print("=" * 50)

==================================================
       PYTHON MATH MODULE METHODS
==================================================

1. Constants
Value of PI = 3.141592653589793
Value of e = 2.718281828459045

2. Logarithmic Functions
Natural Log of 100 = 4.605170185988092
Base-10 Log of 100 = 2.0

3. Exponential Function
exp(2) = 7.38905609893065

4. Power Function
2 raised to the power 5 = 32.0
5 raised to the power 3 = 125.0

5. Rounding Functions
Original Number = 8.65
Ceiling = 9
Floor = 8
Round = 9

Round(8.5) = 8
Round(9.5) = 10

==================================================
Program Completed Successfully
==================================================

In [17]:
import calendar
print(calendar.month(2026, 6))

     June 2026
Mo Tu We Th Fr Sa Su
 1  2  3  4  5  6  7
 8  9 10 11 12 13 14
15 16 17 18 19 20 21
22 23 24 25 26 27 28
29 30

In [18]:
import calendar

year = int(input("Enter the year: "))
print(calendar.calendar(year))

Enter the year:  1947

                                  1947

      January                   February                   March
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
       1  2  3  4  5                      1  2                      1  2
 6  7  8  9 10 11 12       3  4  5  6  7  8  9       3  4  5  6  7  8  9
13 14 15 16 17 18 19      10 11 12 13 14 15 16      10 11 12 13 14 15 16
20 21 22 23 24 25 26      17 18 19 20 21 22 23      17 18 19 20 21 22 23
27 28 29 30 31            24 25 26 27 28            24 25 26 27 28 29 30
                                                    31

       April                      May                       June
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
    1  2  3  4  5  6                1  2  3  4                         1
 7  8  9 10 11 12 13       5  6  7  8  9 10 11       2  3  4  5  6  7  8
14 15 16 17 18 19 20      12 13 14 15 16 17 18       9 10 11 12 13 14 15
21 22 23 24 25 26 27      19 20 21 22 23 24 25      16 17 18 19 20 21 22
28 29 30                  26 27 28 29 30 31         23 24 25 26 27 28 29
                                                    30

        July                     August                  September
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
    1  2  3  4  5  6                   1  2  3       1  2  3  4  5  6  7
 7  8  9 10 11 12 13       4  5  6  7  8  9 10       8  9 10 11 12 13 14
14 15 16 17 18 19 20      11 12 13 14 15 16 17      15 16 17 18 19 20 21
21 22 23 24 25 26 27      18 19 20 21 22 23 24      22 23 24 25 26 27 28
28 29 30 31               25 26 27 28 29 30 31      29 30

      October                   November                  December
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
       1  2  3  4  5                      1  2       1  2  3  4  5  6  7
 6  7  8  9 10 11 12       3  4  5  6  7  8  9       8  9 10 11 12 13 14
13 14 15 16 17 18 19      10 11 12 13 14 15 16      15 16 17 18 19 20 21
20 21 22 23 24 25 26      17 18 19 20 21 22 23      22 23 24 25 26 27 28
27 28 29 30 31            24 25 26 27 28 29 30      29 30 31

In [21]:
import calendar

for day in calendar.day_name:
    print(day)

Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
Sunday

In [22]:
import calendar

for i in range(1, 13):
    print(i, "-", calendar.month_name[i])

1 - January
2 - February
3 - March
4 - April
5 - May
6 - June
7 - July
8 - August
9 - September
10 - October
11 - November
12 - December

In [24]:
import calendar

count = calendar.leapdays(2000, 2026)

print("Leap Years =", count)

Leap Years = 7

In [4]:
a=int(input("Enter the value"))
print(a)

Enter the value a

ValueError: invalid literal for int() with base 10: 'a'

# EXCEPTION HANDLING

In [9]:
try:
    num = int(input("Enter a number: "))
    print("You entered:", num)
except ValueError:
    print("Please enter only numbers.")

Enter a number:  hi

Please enter only numbers.

In [13]:
try:
    a = int(input("Enter first number: "))
    b = int(input("Enter second number: "))

    result = a / b
    print("Result =", result)

except ZeroDivisionError:
    print("Cannot divide by zero.")

Enter first number:  10
Enter second number:  0

Cannot divide by zero.

In [ ]:
try:
    num1 = int(input("Enter first number: "))
    num2 = int(input("Enter second number: "))

    print("Answer =", num1 / num2)

except ValueError:
    print("Invalid input! Enter only integers.")

except ZeroDivisionError:
    print("Second number cannot be zero.")

In [16]:
try:
    file = open("sample.txt", "r")
    print(file.read())

except FileNotFoundError:
    print("File not found.")

finally:
    print("Program Finished.")

File not found.
Program Finished.

# Examples for NumPy

In [25]:
import numpy as np
print(np.__version__)

1.26.4

In [27]:
#Example finding type of ndarray
import numpy as np
arr=np.array((10,20,30))
print(arr)

print(type(arr))

[10 20 30]
<class 'numpy.ndarray'>

# Array Attributes
# shape, size, ndim, dtype, itemsize

In [33]:
# example of ndim
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3

In [36]:
# Example of shape
import numpy as np

arr = np.array([[10, 20, 30,40],
                [40, 50, 60,50]])

print(arr.shape)

(2, 4)

In [43]:
#Example for Size
import numpy as np

arr = np.array([[100, 200, 300],[400, 500, 600]])

print(arr.size)

6

In [41]:
# Example of dtype
import numpy as np

arr = np.array([10, 20, 30])

print(arr.dtype)

int32

In [60]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6

In [ ]:
#Example for Accessing
import numpy as np

arr = np.array([10, 20, 30, 40])

print(arr[0])
print(arr[2])

In [44]:
#Example for array indexing 
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7

In [ ]:
#example for accessinf 2d 
import numpy as np

arr = np.array([[10, 20, 30],[40, 50, 60],[70, 80, 90]])

print(arr[0][0])  
print(arr[1][2])  
print(arr[2][1])

In [ ]:
import numpy as np

arr = np.array([[10, 20, 30],[40, 50, 60],[70, 80, 90]])

print(arr[0, 2])
print(arr[1, 1])
print(arr[2, 0])

In [46]:
#Access an Entire Row
import numpy as np

arr = np.array([[10, 20, 30],[40, 50, 60],[70, 80, 90]])

print(arr[0])   
print(arr[2])

[10 20 30]
[70 80 90]

In [47]:
#Access an Entire Column
import numpy as np

arr = np.array([[11, 22, 32],[40, 50, 60],[70, 80, 90]])

print(arr[:, 0])   
print(arr[:, 2])

[11 40 70]
[32 60 90]

In [48]:
import numpy as np

arr = np.array([[10, 20, 30],[40, 50, 60],[70, 80, 90]])

print(arr[0:2, 1:3])

'''
0:2 → Rows 0 and 1
1:3 → Columns 1 and 2
'''

[[20 30]
 [50 60]]

In [49]:
#Real-Time example
import numpy as np

marks = np.array([[85, 90, 88],[78, 80, 82],[92, 95, 91]])

print("First student's marks:", marks[0])
print("Second student's Science marks:", marks[1, 1])
print("All students' English marks:", marks[:, 2])

First student's marks: [85 90 88]
Second student's Science marks: 80
All students' English marks: [88 82 91]

In [ ]:
#Negative Indexing
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr[-1, -1])

In [51]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])

[5 6]

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

In [53]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]

In [56]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]

In [58]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]

In [59]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]

In [64]:
#Example for NumPy Array Iterating
#1D Array

import numpy as np

arr = np.array([10, 20, 30, 40, 50])

for i in arr:
    print(i)

10
20
30
40
50

In [63]:
#Iterating Through a 2D Array
import numpy as np

arr = np.array([[10, 20, 30],
                [40, 50, 60]])

for row in arr:
    print(row)

[10 20 30]
[40 50 60]

In [70]:
#Iterating Through Every Element in a 2D Array
import numpy as np

arr = np.array([[10, 20, 30],
                [40, 50, 60]])

for row in arr:
    for element in row:
        print(element)

10
20
30
40
50
60

In [71]:
#Iterating Through a 3D Array
import numpy as np

arr = np.array([[[1, 2], [3, 4]],[[5, 6], [7, 8]]])

for matrix in arr:
    print(matrix)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]

In [72]:
# Iterating Every Element of a 3D Array
import numpy as np

arr = np.array([[[1, 2], [3, 4]],[[5, 6], [7, 8]]])

for matrix in arr:
    for row in matrix:
        for element in row:
            print(element)

1
2
3
4
5
6
7
8

# NumPy Joining Array

# Joining means combining two or more NumPy arrays into a single array.
# NumPy provides the following functions for joining arrays:

# np.concatenate()
# np.stack()
# np.hstack()
# np.vstack()
# np.dstack()

In [65]:
#Joining Two 1D Arrays using concatenate()

import numpy as np
arr1 = np.array([10, 20, 30])
arr2 = np.array([40, 50, 60])

result = np.concatenate((arr1, arr2))

print(result)

[10 20 30 40 50 60]

In [69]:
#Joining Two 2D Arrays (Row-wise)

import numpy as np

arr1 = np.array([[10, 20],[30, 40]])
arr2 = np.array([[50, 60],[70, 80]])

result = np.concatenate((arr1, arr2), axis=0)

print(result)

[[10 20]
 [30 40]
 [50 60]
 [70 80]]

In [73]:
#Using stack()
import numpy as np

arr1 = np.array([10, 20, 30])
arr2 = np.array([40, 50, 60])

result = np.stack((arr1, arr2))

print(result)

[[10 20 30]
 [40 50 60]]

In [ ]:
#Using hstack() (Horizontal Stack)
import numpy as np

arr1 = np.array([10, 20, 30])
arr2 = np.array([40, 50, 60])

result = np.hstack((arr1, arr2))

print(result)

In [74]:
#Using vstack() (Vertical Stack)
import numpy as np

arr1 = np.array([10, 20, 30])
arr2 = np.array([40, 50, 60])

result = np.vstack((arr1, arr2))

print(result)

[[10 20 30]
 [40 50 60]]

In [ ]:
# Using dstack() (Depth Stack)
import numpy as np

arr1 = np.array([10, 20, 30])
arr2 = np.array([40, 50, 60])

result = np.dstack((arr1, arr2))

print(result)

In [75]:
#Real-Time Example (Sales Data)
import numpy as np

branch1 = np.array([[1000, 1500],[1200, 1800]])

branch2 = np.array([[1300, 1700],[1400, 1600]])

sales = np.concatenate((branch1, branch2), axis=0)

print(sales)

[[1000 1500]
 [1200 1800]
 [1300 1700]
 [1400 1600]]

In [ ]:
'''
A college conducted two internal exams for the same students.
Internal Exam 1 Marks
Internal Exam 2 Marks
Your task is to combine both exam marks into a single NumPy array.
Input
Exam1 = [78, 85, 90, 88, 76]
Exam2 = [80, 82, 91, 87, 79]
'''

import numpy as np

exam1 = np.array([78, 85, 90, 88, 76])
exam2 = np.array([80, 82, 91, 87, 79])

combined_marks = np.concatenate((exam1, exam2))

print("Exam 1 Marks:", exam1)
print("Exam 2 Marks:", exam2)
print("Combined Marks:", combined_marks)

# NumPy Splitting Array

# Splitting means dividing one NumPy array into two or more smaller arrays.
# NumPy provides the following functions for splitting arrays:

# np.array_split()
# np.split()
# np.hsplit()
# np.vsplit()
# np.dsplit()

In [80]:
# Splitting a 1D Array using array_split()

import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60])
result = np.array_split(arr, 3)

print(result)

[array([10, 20]), array([30, 40]), array([50, 60])]

# NumPy Searching Arrays
# Searching means finding the position (index) of one or more elements in a NumPy array.
# NumPy provides several functions for searching arrays:

# np.where()
# np.searchsorted()
# np.nonzero()

In [81]:
# Example: Find the Index of 30
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
result = np.where(arr == 30)

print(result)

(array([2], dtype=int64),)

In [82]:
# Find Multiple Values
import numpy as np

arr = np.array([10, 20, 30, 20, 40, 20])
result = np.where(arr == 20)

print(result)

(array([1, 3, 5], dtype=int64),)

In [84]:
#Find Even Numbers
import numpy as np

arr = np.array([11, 20, 35, 40, 55, 60])

result = np.where(arr % 2 == 0)

print(result)

(array([0, 2, 4], dtype=int64),)

In [85]:
#Using searchsorted()

import numpy as np
arr = np.array([10, 20, 30, 40, 50])
result = np.searchsorted(arr, 35)
print(result)

3

In [88]:
#Using nonzero()
#nonzero() returns the indices of all non-zero elements.

import numpy as np

arr = np.array([10, 0, 20, 0, 30])

result = np.nonzero(arr)

print(result)

(array([0, 2, 4], dtype=int64),)

In [89]:
'''
Real-Time Example: Student Marks
Find the students who scored 90 marks.
'''
import numpy as np

marks = np.array([85, 90, 78, 90, 95])
result = np.where(marks == 90)
print("Students with 90 marks are at indices:", result[0])

Students with 90 marks are at indices: [1 3]

In [1]:
'''
Student Attendance Analysis
A teacher records attendance for 10 students:
1 = Present
0 = Absent
attendance = np.array([1, 0, 1, 1, 0, 1, 0, 1, 1, 0])

Task
Find the indices of all present students.
Find the indices of all absent students.
Count the number of present students.
Count the number of absent students.
'''

import numpy as np

attendance = np.array([1, 0, 1, 1, 0, 1, 0, 1, 1, 0])

present = np.where(attendance == 1)
absent = np.where(attendance == 0)

print("Present Student Indices:", present[0])
print("Absent Student Indices:", absent[0])

print("Total Present:", len(present[0]))
print("Total Absent:", len(absent[0]))

Present Student Indices: [0 2 3 5 7 8]
Absent Student Indices: [1 4 6 9]
Total Present: 6
Total Absent: 4

# NumPy Filter Array
# Filtering means selecting specific elements from a NumPy array based on a condition.
# In NumPy, filtering is done using a Boolean Index Array.

In [ ]:
# Filter Even Numbers
import numpy as np
arr = np.array([10, 15, 20, 25, 30, 35])
result = arr[arr % 2 == 0]

print(result)

In [ ]:
# Filter Odd Numbers
import numpy as np
arr = np.array([10, 15, 20, 25, 30, 35])
result = arr[arr % 2 != 0]

print(result)

In [1]:
# Filter Numbers Greater Than 50

import numpy as np
arr = np.array([25, 45, 60, 80, 35, 90])
result = arr[arr > 50]

print(result)

[60 80 90]

In [ ]:
# Filter Numbers Less Than 30

import numpy as np
arr = np.array([10, 25, 40, 50, 20])
result = arr[arr < 30]

print(result)

In [6]:
# Boolean Indexing

import numpy as np
arr = np.array([10, 20, 30, 40])

filter_array = [True, False, True, False]

print(arr[filter_array])

[10 20 30]

In [13]:
# Filter Strings

import numpy as np
fruits = np.array(["Apple", "Banana", "Mango", "Orange","Mango"])
result = fruits[fruits == "Mango"]

print(result)

['Mango' 'Mango']

In [15]:
# Filter a 2D Array

import numpy as np
arr = np.array([[40, 20],[30, 40]])
result = arr[arr > 20]

print(result)

[40 30 40]

In [16]:

# Real-Time Example: Employee Salaries
# Display salaries greater than ₹30,000.

import numpy as np
salary = np.array([25000, 32000, 28000, 40000, 35000])
high_salary = salary[salary > 30000]

print(high_salary)

[32000 40000 35000]

In [20]:
"""
Student Result Analysis
A college stores the marks of students in a NumPy array.
marks = np.array([45, 78, 90, 35, 88, 55, 92, 40, 81, 67])

Task
Display all student marks.
Display only the students who passed (marks ≥ 50).
Display only the students who scored above 80.
Display only the students who failed (marks < 50).
Count the number of passed students.
Count the number of failed students.
"""


import numpy as np

marks = np.array([45, 78, 90, 35, 88, 55, 92, 40, 81, 67])

passed = marks[marks >= 50]
failed = marks[marks < 50]
above80 = marks[marks > 80]

print("All Marks:", marks)
print("Passed Students:", passed)
print("Students Above 80:", above80)
print("Failed Students:", failed)

print("Total Passed:", len(passed))
print("Total Failed:", len(failed))

All Marks: [45 78 90 35 88 55 92 40 81 67]
Passed Students: [78 90 88 55 92 81 67]
Students Above 80: [90 88 92 81]
Failed Students: [45 35 40]
Total Passed: 7
Total Failed: 3

# Pandas
# one of the most important libraries for Data Analysis, Data Science, and Machine Learning.

In [21]:
import pandas as pd

print(pd.__version__)

2.2.2

In [ ]:
Common Pandas Methods

1. Creating Data

pd.Series()	Create a Series
pd.DataFrame()	Create a DataFrame
pd.read_csv()	Read a CSV file
pd.read_excel()	Read an Excel file
pd.read_json()	Read a JSON file

2. Viewing Data

Method      	Description
head()	       Display the first 5 rows
tail()	       Display the last 5 rows
sample()	   Display random rows
info()	       Show dataset information
describe()	   Show statistical summary
shape	       Returns (rows, columns)
columns	       Returns column names
index	       Returns row indexes
dtypes	       Shows the data type of each column


3. Selecting Data

Method	    Description
loc[]	    Select rows and columns using labels
iloc[]	    Select rows and columns using index positions
[]	        Select one or more columns


4. Filtering Data

Method	    Description
query()	    Filter using conditions
isin()	    Check if values exist
between()	Check values within a range


5. Sorting Data

Method       	Description
sort_values()	Sort rows by column values
sort_index()	Sort by index

6. Adding and Removing Data

Method	     Description
insert()	 Insert a new column
drop()	     Remove rows or columns
rename()	 Rename columns
assign()	 Add a new column


7. Missing Values

Method	    Description
isnull()	Find missing values
notnull()	Find non-missing values
fillna()	Replace missing values
dropna()	Remove missing values

8. Mathematical Methods

Method	   Description
sum()	   Total
mean()	   Average
max()	   Highest value
min()	   Lowest value
count()	   Count values
std()	    Standard deviation
median()	Median


9. Value Analysis

Method	          Description
value_counts()	  Count unique values
unique()	      Display unique values
nunique()	      Count unique values

10. Grouping Data

Method	     Description
groupby()	  Group data


11. Combining DataFrames

Method	     Description
concat()	 Combine DataFrames
merge()	     Merge DataFrames
join()	     Join DataFrames

12. Saving Data

Method	     Description
to_csv()	 Save as CSV
to_excel()	 Save as Excel

In [22]:
# Create a Series
import pandas as pd
data = [10, 20, 30, 40, 50]
s = pd.Series(data)
print(s)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [23]:
# Custom Index
import pandas as pd
marks = [85, 90, 78]

s = pd.Series(marks, index=["Ali", "Rahul", "Anil"])

print(s)

Ali      85
Rahul    90
Anil     78
dtype: int64

In [24]:
# Access Data
import pandas as pd
marks = pd.Series([85, 90, 78])

print(marks[0])
print(marks[2])

85
78

In [25]:
# Access Using Labels
import pandas as pd

marks = pd.Series([85, 90, 78],index=["Ramu", "Rahul", "Anil"])

print(marks["Rahul"])

In [26]:
# Create a Series from a Dictionary
import pandas as pd

student = {
    "Name": "Naresh",
    "Age": 21,
    "Course": "BCA"
}

s = pd.Series(student)

print(s)

Name      Naresh
Age           21
Course       BCA
dtype: object

# What is a DataFrame?

# A DataFrame is a 2-dimensional table (rows and columns), similar to an Excel sheet.

In [27]:
# Create a DataFrame
import pandas as pd

data = {
    "Name": ["Rahul", "Anil", "Priya"],
    "Age": [20, 21, 19],
    "Marks": [85, 90, 88]
}

df = pd.DataFrame(data)

print(df)

    Name  Age  Marks
0  Rahul   20     85
1   Anil   21     90
2  Priya   19     88

In [29]:
# Display Only One Column
import pandas as pd

data = {
    "Name": ["Rahul", "Anil", "Priya"],
    "Marks": [85, 90, 88]
}

df = pd.DataFrame(data)
print(df["Marks"])

0    85
1    90
2    88
Name: Marks, dtype: int64

In [30]:
# Real-Time Example
# Employee Details
import pandas as pd

employee = {
    "ID": [101, 102, 103],
    "Name": ["Amit", "Neha", "Ravi"],
    "Salary": [25000, 30000, 28000]
}

df = pd.DataFrame(employee)

print(df)

    ID  Name  Salary
0  101  Amit   25000
1  102  Neha   30000
2  103  Ravi   28000

In [32]:
import pandas as pd

df = pd.read_csv("StudentData.CSV")

print(df)

  Stu_Name  RegNum Section  Branch
0     Rama    1234        A    CSE
1     Rama    1234        A    CSE
2     Rama    1234        A    CSE
3     Rama    1234        A    CSE
4     Rama    1234        A    CSE
5     Rama    1234        A    CSE
6     Rama    1234        A    CSE

In [33]:
import pandas as pd

df=pd.read_csv("StudentData.CSV")
print(df)

  Stu_Name  RegNum Section  Branch
0     Rama    1234        A    CSE
1     Rama    1234        A    CSE
2     Rama    1234        A    CSE
3     Rama    1234        A    CSE
4     Rama    1234        A    CSE
5     Rama    1234        A    CSE
6     Rama    1234        A    CSE

In [36]:
import pandas as pd

df=pd.read_excel("students_sample.xlsx")
print(df)

    Name  Age Course  Marks
0  Rahul   20    BCA     85
1   Anil   21    BCA     90
2  Priya   19    BCA     88
3  Sneha   20    BCA     92
4  Kiran   22    BCA     80

In [37]:
import pandas as pd
df=pd.read_json("students_sample.json")
print(df)

    Name  Age Course  Marks
0  Rahul   20    BCA     85
1   Anil   21    BCA     90
2  Priya   19    BCA     88
3  Sneha   20    BCA     92
4  Kiran   22    BCA     80

In [46]:
# Sample DataFrame


import pandas as pd

data = {
    "Name": ["Rahul", "Anil", "Priya", "Sneha", "Kiran", "Ravi"],
    "Age": [20, 21, 19, 22, 20, 23],
    "Course": ["BCA", "BCA", "BCA", "BCA", "BCA", "BCA"],
    "Marks": [85, 90, 88, 92, 80, 75]
}

df = pd.DataFrame(data)

print(df)
print("="*30)
#head()
#Displays the first 5 rows by default.

print(df.head())
print("="*30)


#tail()
#Displays the last 5 rows.
print(df.tail())
print()


# Display Last 2 Rows
print(df.tail(2))
print("="*50)

#sample()
#Displays random row(s).
print(df.sample())
print("="*50)


#info()
#Displays information about the DataFrame.
print(df.info())
print("="*50)

#describe()
#Displays the statistical summary of numeric columns.
print(df.describe())

#shape
#Returns the number of rows and columns.
print(df.shape)

    Name  Age Course  Marks
0  Rahul   20    BCA     85
1   Anil   21    BCA     90
2  Priya   19    BCA     88
3  Sneha   22    BCA     92
4  Kiran   20    BCA     80
5   Ravi   23    BCA     75
==============================
    Name  Age Course  Marks
0  Rahul   20    BCA     85
1   Anil   21    BCA     90
2  Priya   19    BCA     88
3  Sneha   22    BCA     92
4  Kiran   20    BCA     80
==============================
    Name  Age Course  Marks
1   Anil   21    BCA     90
2  Priya   19    BCA     88
3  Sneha   22    BCA     92
4  Kiran   20    BCA     80
5   Ravi   23    BCA     75

    Name  Age Course  Marks
4  Kiran   20    BCA     80
5   Ravi   23    BCA     75
==================================================
    Name  Age Course  Marks
2  Priya   19    BCA     88
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    6 non-null      object
 1   Age     6 non-null      int64
 2   Course  6 non-null      object
 3   Marks   6 non-null      int64
dtypes: int64(2), object(2)
memory usage: 324.0+ bytes
None
==================================================
             Age      Marks
count   6.000000   6.000000
mean   20.833333  85.000000
std     1.471960   6.449806
min    19.000000  75.000000
25%    20.000000  81.250000
50%    20.500000  86.500000
75%    21.750000  89.500000
max    23.000000  92.000000
(6, 4)

In [ ]:
Write a Python program using Pandas to perform the following operations:

Read the Excel file.
Display the first 5 student records.
Display the last 3 student records.
Display any 2 random student records.
Display the complete information of the dataset.
Display the statistical summary.
Display the total number of rows and columns.
Display all column names.
Display the row indexes.
Display the data type of each column.

In [48]:
# Pandas – Selecting Data
import pandas as pd

data = {
    "Name": ["Rahul", "Anil", "Priya", "Sneha", "Kiran", "Ravi"],
    "Age": [20, 21, 19, 22, 20, 23],
    "Course": ["BCA", "BCA", "BCA", "BCA", "BCA", "BCA"],
    "Marks": [85, 90, 88, 92, 80, 75]
}

df = pd.DataFrame(data)

print(df)
print("-"*50)

#Using [] (Select Columns)
#Select One Column
print(df["Name"])

#Select Multiple Columns
print(df[["Name", "Marks"]])

    Name  Age Course  Marks
0  Rahul   20    BCA     85
1   Anil   21    BCA     90
2  Priya   19    BCA     88
3  Sneha   22    BCA     92
4  Kiran   20    BCA     80
5   Ravi   23    BCA     75
--------------------------------------------------
0    Rahul
1     Anil
2    Priya
3    Sneha
4    Kiran
5     Ravi
Name: Name, dtype: object

#  iloc[]
# iloc[] selects data using integer index positions.

# Syntax
# df.iloc[row_position, column_position]

In [54]:
#Select One Row
print(df.iloc[2])

Name      Priya
Age          19
Course      BCA
Marks        88
Name: 2, dtype: object

In [55]:
#Select Multiple Rows
print(df.iloc[1:4])

    Name  Age Course  Marks
1   Anil   21    BCA     90
2  Priya   19    BCA     88
3  Sneha   22    BCA     92

In [57]:
print(df.iloc[:, [1, 3]])

   Age  Marks
0   20     85
1   21     90
2   19     88
3   22     92
4   20     80
5   23     75

In [63]:
print(df)
print("[1:4, 1:5]")
print("="*50)

#Example select Row and Col
print(df.iloc[1:4, 1:5])

    Name  Age Course  Marks
0  Rahul   20    BCA     85
1   Anil   21    BCA     90
2  Priya   19    BCA     88
3  Sneha   22    BCA     92
4  Kiran   20    BCA     80
5   Ravi   23    BCA     75
[1:4, 1:5]
==================================================
   Age Course  Marks
1   21    BCA     90
2   19    BCA     88
3   22    BCA     92

# Filtering Data

In [68]:
import pandas as pd

data = {
    "ID": [101, 102, 103, 104, 105, 106],
    "Name": ["Rahul", "Anil", "Priya", "Sneha", "Kiran", "Ravi"],
    "Department": ["BCA", "BCA", "B.Sc", "B.Com", "BCA", "B.Sc"],
    "Marks": [85, 90, 78, 92, 80, 75],
    "City": ["Belagavi", "Hubli", "Dharwad", "Belagavi", "Hubli", "Gadag"]
}

df = pd.DataFrame(data)

print(df)

    ID   Name Department  Marks      City
0  101  Rahul        BCA     85  Belagavi
1  102   Anil        BCA     90     Hubli
2  103  Priya       B.Sc     78   Dharwad
3  104  Sneha      B.Com     92  Belagavi
4  105  Kiran        BCA     80     Hubli
5  106   Ravi       B.Sc     75     Gadag

In [71]:
#query()
'''
query() filters rows based on a condition written as a string.
Syntax
df.query("condition")
'''

# Students with Marks Greater Than 80
print(df.query("Marks > 80"))

# Students from BCA Department
print(df.query("Department == 'BCA'"))

#Multiple Conditions
print(df.query("Department == 'BCA' and Marks >= 85"))

    ID   Name Department  Marks      City
0  101  Rahul        BCA     85  Belagavi
1  102   Anil        BCA     90     Hubli
3  104  Sneha      B.Com     92  Belagavi
    ID   Name Department  Marks      City
0  101  Rahul        BCA     85  Belagavi
1  102   Anil        BCA     90     Hubli
4  105  Kiran        BCA     80     Hubli
    ID   Name Department  Marks      City
0  101  Rahul        BCA     85  Belagavi
1  102   Anil        BCA     90     Hubli

In [72]:
# isin()
'''
isin() checks whether values exist in a given list.

Syntax
df[column].isin(list)
'''

#Students from Hubli or Gadag
print(df[df["City"].isin(["Hubli", "Gadag"])])

#Students from BCA or B.Sc
print(df[df["Department"].isin(["BCA", "B.Sc"])])

    ID   Name Department  Marks   City
1  102   Anil        BCA     90  Hubli
4  105  Kiran        BCA     80  Hubli
5  106   Ravi       B.Sc     75  Gadag
    ID   Name Department  Marks      City
0  101  Rahul        BCA     85  Belagavi
1  102   Anil        BCA     90     Hubli
2  103  Priya       B.Sc     78   Dharwad
4  105  Kiran        BCA     80     Hubli
5  106   Ravi       B.Sc     75     Gadag

In [73]:
#between()
'''
between() selects values that lie within a specified range.

Syntax
df[column].between(start, end)
'''
#Marks Between 80 and 90
print(df[df["Marks"].between(80, 90)])

# ID Between 102 and 105
print(df[df["ID"].between(102, 105)])

    ID   Name Department  Marks      City
0  101  Rahul        BCA     85  Belagavi
1  102   Anil        BCA     90     Hubli
4  105  Kiran        BCA     80     Hubli
    ID   Name Department  Marks      City
1  102   Anil        BCA     90     Hubli
2  103  Priya       B.Sc     78   Dharwad
3  104  Sneha      B.Com     92  Belagavi
4  105  Kiran        BCA     80     Hubli

In [ ]:
Order_ID Customer Category  Amount      City
0      1001    Rahul   Mobile   15000     Hubli
1      1002     Anil   Laptop   55000  Belagavi
2      1003    Priya   Tablet   25000   Dharwad
3      1004    Sneha   Laptop   65000     Hubli
4      1005    Kiran   Mobile   18000     Gadag
5      1006     Ravi    Watch    8000  Belagavi
6      1007    Pooja   Laptop   72000     Hubli
7      1008    Akash   Tablet   22000   Dharwad


Task
Display orders where the amount is greater than ₹20,000.
Display orders where the amount is between ₹15,000 and ₹50,000.
Display customers who purchased Laptops.
Display customers who purchased Mobile or Tablet.
Display orders from Hubli.
Display Laptop orders worth more than ₹60,000.
Display customers from Hubli or Belagavi.
Count orders where the amount is above ₹25,000.
Display orders whose amount is not between ₹20,000 and ₹60,000.
Display customers who purchased a Laptop and are from Hubli.

In [95]:
import pandas as pd

orders = {
    "Order_ID":[1001,1002,1003,1004,1005,1006,1007,1008],
    "Customer":["Rahul","Anil","Priya","Sneha","Kiran","Ravi","Pooja","Akash"],
    "Category":["Mobile","Laptop","Tablet","Laptop","Mobile","Watch","Laptop","Tablet"],
    "Amount":[15000,55000,25000,65000,18000,8000,72000,22000],
    "City":["Hubli","Belagavi","Dharwad","Hubli","Gadag","Belagavi","Hubli","Dharwad"]
}

df = pd.DataFrame(orders)
print(df)
print("="*50)

# Display orders where the amount is greater than ₹20,000.
print(df.query("Amount > 20000"))
print("="*50)

# Display orders where the amount is between ₹15,000 and ₹50,000.
print(df[df["Amount"].between(15000, 50000)])
print("="*50)

#Display customers who purchased Laptops.
print(df.query("Category == 'Laptop'"))
print("=="*30)

#Display customers who purchased Mobile or Tablet.
print(df[df["Category"].isin(["Mobile", "Tablet"])])
print("=="*30)

#Display orders from Hubli.
print(df.query("City == 'Hubli'"))
print("=="*30)

#Display customers from Hubli or Belagavi.
print(df[df["City"].isin(["Hubli", "Belagavi"])])
print("=="*30)

#Display Laptop orders worth more than ₹60,000.
print(df.query("Category == 'Laptop' and Amount > 60000"))
print("=="*30)

#Count orders where the amount is above ₹25,000.
count = df.query("Amount > 25000").shape[0]
print("Total Orders:", count)
print("=="*30)

#Display orders whose amount is not between ₹20,000 and ₹60,000.
print(df[~df["Amount"].between(20000, 60000)])
print("=="*30)

#Display customers who purchased a Laptop and are from Hubli.
print(df.query("Category == 'Laptop' and City == 'Hubli'"))

   Order_ID Customer Category  Amount      City
0      1001    Rahul   Mobile   15000     Hubli
1      1002     Anil   Laptop   55000  Belagavi
2      1003    Priya   Tablet   25000   Dharwad
3      1004    Sneha   Laptop   65000     Hubli
4      1005    Kiran   Mobile   18000     Gadag
5      1006     Ravi    Watch    8000  Belagavi
6      1007    Pooja   Laptop   72000     Hubli
7      1008    Akash   Tablet   22000   Dharwad
==================================================
   Order_ID Customer Category  Amount      City
1      1002     Anil   Laptop   55000  Belagavi
2      1003    Priya   Tablet   25000   Dharwad
3      1004    Sneha   Laptop   65000     Hubli
6      1007    Pooja   Laptop   72000     Hubli
7      1008    Akash   Tablet   22000   Dharwad
==================================================
   Order_ID Customer Category  Amount     City
0      1001    Rahul   Mobile   15000    Hubli
2      1003    Priya   Tablet   25000  Dharwad
4      1005    Kiran   Mobile   18000    Gadag
7      1008    Akash   Tablet   22000  Dharwad
==================================================
   Order_ID Customer Category  Amount      City
1      1002     Anil   Laptop   55000  Belagavi
3      1004    Sneha   Laptop   65000     Hubli
6      1007    Pooja   Laptop   72000     Hubli
============================================================
   Order_ID Customer Category  Amount     City
0      1001    Rahul   Mobile   15000    Hubli
2      1003    Priya   Tablet   25000  Dharwad
4      1005    Kiran   Mobile   18000    Gadag
7      1008    Akash   Tablet   22000  Dharwad
============================================================
   Order_ID Customer Category  Amount   City
0      1001    Rahul   Mobile   15000  Hubli
3      1004    Sneha   Laptop   65000  Hubli
6      1007    Pooja   Laptop   72000  Hubli
============================================================
   Order_ID Customer Category  Amount      City
0      1001    Rahul   Mobile   15000     Hubli
1      1002     Anil   Laptop   55000  Belagavi
3      1004    Sneha   Laptop   65000     Hubli
5      1006     Ravi    Watch    8000  Belagavi
6      1007    Pooja   Laptop   72000     Hubli
============================================================
   Order_ID Customer Category  Amount   City
3      1004    Sneha   Laptop   65000  Hubli
6      1007    Pooja   Laptop   72000  Hubli
============================================================
Total Orders: 3
============================================================
   Order_ID Customer Category  Amount      City
0      1001    Rahul   Mobile   15000     Hubli
3      1004    Sneha   Laptop   65000     Hubli
4      1005    Kiran   Mobile   18000     Gadag
5      1006     Ravi    Watch    8000  Belagavi
6      1007    Pooja   Laptop   72000     Hubli
============================================================
   Order_ID Customer Category  Amount   City
3      1004    Sneha   Laptop   65000  Hubli
6      1007    Pooja   Laptop   72000  Hubli

# Sorting Data
# Sorting is used to arrange data in ascending or descending order.

In [99]:
import pandas as pd

student = {
    "ID": [101, 102, 103, 104, 105],
    "Name": ["Rahul", "Anil", "Priya", "Sneha", "Kiran"],
    "Age": [20, 21, 19, 22, 20],
    "Department": ["BCA", "BCA", "B.Sc", "B.Com", "BCA"],
    "Marks": [85, 90, 78, 92, 80]
}

df = pd.DataFrame(student)

'''
sort_values()
Syntax
df.sort_values(by="Column_Name")
'''
#Sort by Marks (Ascending)
print(df.sort_values(by="Marks"))

#Sort by Marks (Descending)
print(df.sort_values(by="Marks", ascending=False))


#Sort by Name
print(df.sort_values(by="Name"))


# sort_index()
'''
Syntax
df.sort_index()
'''
df.sort_index()

    ID   Name  Age Department  Marks
2  103  Priya   19       B.Sc     78
4  105  Kiran   20        BCA     80
0  101  Rahul   20        BCA     85
1  102   Anil   21        BCA     90
3  104  Sneha   22      B.Com     92
    ID   Name  Age Department  Marks
3  104  Sneha   22      B.Com     92
1  102   Anil   21        BCA     90
0  101  Rahul   20        BCA     85
4  105  Kiran   20        BCA     80
2  103  Priya   19       B.Sc     78
    ID   Name  Age Department  Marks
1  102   Anil   21        BCA     90
4  105  Kiran   20        BCA     80
2  103  Priya   19       B.Sc     78
0  101  Rahul   20        BCA     85
3  104  Sneha   22      B.Com     92

    ID   Name  Age Department  Marks
0  101  Rahul   20        BCA     85
1  102   Anil   21        BCA     90
2  103  Priya   19       B.Sc     78
3  104  Sneha   22      B.Com     92
4  105  Kiran   20        BCA     80

# Mathematical Methods
# Pandas provides several mathematical methods to perform calculations on numerical data.
# These methods help us analyze datasets by finding totals, averages, highest values, lowest values,
# counts, and other statistical information.

In [121]:
import pandas as pd

employee = {
    "Emp_ID": [101, 102, 103, 104, 105],
    "Name": ["Amit", "Neha", "Ravi", "Pooja", "Karan"],
    "Department": ["HR", "IT", "Finance", "IT", "HR"],
    "Salary": [25000, 40000, 35000, 50000, 28000],
    "Experience": [2, 5, 4, 8, 3]
}

df = pd.DataFrame(employee)

print(df)

   Emp_ID   Name Department  Salary  Experience
0     101   Amit         HR   25000           2
1     102   Neha         IT   40000           5
2     103   Ravi    Finance   35000           4
3     104  Pooja         IT   50000           8
4     105  Karan         HR   28000           3

In [ ]:
# sum()
# Returns the total of all values in a column.
'''
Syntax
df["Salary"].sum()
'''
print("Total Salary =", df["Salary"].sum())

# mean()
# Returns the average of all values.
'''
Syntax
df["Salary"].mean()
'''

print("Average Salary =", df["Salary"].mean())

# max()
# Returns the highest value.
print("Highest Salary =", df["Salary"].max())

# min()
# Returns the lowest value.
print("Lowest Salary =", df["Salary"].min())

#count()
#Returns the number of non-missing values.
print("Number of Employees =", df["Salary"].count())

#std()
# Returns the standard deviation, which shows how spread out the values are from the average.
print("Standard Deviation =", df["Salary"].std())

# median()
# Returns the middle value after sorting the data.
print("Median Salary =", df["Salary"].median())

# Adding and Removing Data
# In Pandas, we can easily modify a DataFrame by adding new columns, removing rows or columns, renaming existing columns, or creating new columns based on existing data.

In [107]:
#insert()
'''
The insert() method is used to add a new column at a specific position in the DataFrame.

Syntax
df.insert(position, "Column_Name", values)
'''

#Insert Age Column
df.insert(2, "Age1", [20, 21, 19, 22, 20])
print(df)

'''
drop()
The drop() method removes rows or columns from a DataFrame.

Syntax
df.drop("Column_Name", axis=1)
axis=0 → Remove rows
axis=1 → Remove column
'''

#Remove Department Column
df.drop("Department", axis=1)

#Remove Third Row
df.drop(2)

#Remove Multiple Columns
df.drop(["Age", "City"], axis=1)

#---------------------------------
#rename()
'''
The rename() method changes the names of columns.

Syntax
df.rename(columns={"Old_Name": "New_Name"})
'''
#Rename Marks to Score
df.rename(columns={"Marks": "Score"})

#Rename Multiple Columns
df.rename(columns={
    "Name": "Student_Name",
    "Department": "Course"
})

#----------------------------
#assign()
'''
The assign() method adds a new column to a DataFrame and returns a new DataFrame.

Syntax
df = df.assign(Column_Name=values)
'''
# Add City Column
df = df.assign(
    City=["Belagavi", "Hubli", "Dharwad", "Belagavi", "Hubli"]
)


#Add Result Column
df = df.assign(
    Result=["Pass", "Pass", "Pass", "Pass", "Pass"]
)

#Add Grade Column
df = df.assign(Grade=df["Marks"].apply(lambda x: "A" if x >= 90 else "B"))

'\n#Insert Age Column\ndf.insert(2, "Age1", [20, 21, 19, 22, 20])\nprint(df)\n'

In [ ]:
Real-Time Task: Employee Management System

	Emp_ID	Name	Department	Salary
0	101	Amit	HR	25000
1	102	Neha	IT	40000
2	103	Ravi	Finance	35000
3	104	Pooja	IT	50000
4	105	Karan	HR	28000

Tasks
Insert a new column Age after the Name column.
Insert a new column City at the last position.
Remove the Department column.
Remove the employee with index 2.
Rename the Salary column to Monthly_Salary.
Rename the Name column to Employee_Name.
Add a new column Bonus using assign() with values [2000, 3000, 2500, 4000, 2200].
Create a new column Total_Salary = Salary + Bonus.
Create a new column Tax equal to 10% of Salary.
Display the final DataFrame.

In [108]:
import pandas as pd

# Create DataFrame
employee = {
    "Emp_ID": [101,102,103,104,105],
    "Name": ["Amit","Neha","Ravi","Pooja","Karan"],
    "Department": ["HR","IT","Finance","IT","HR"],
    "Salary": [25000,40000,35000,50000,28000]
}

df = pd.DataFrame(employee)

print("Original DataFrame")
print(df)

# ----------------------------------------------------
# 1. Insert a new column Age after the Name column
# ----------------------------------------------------
df.insert(2, "Age", [25, 30, 28, 35, 27])

print("\n1. Age Column Added")
print(df)

# ----------------------------------------------------
# 2. Insert a new column City at the last position
# ----------------------------------------------------
df.insert(len(df.columns), "City",
          ["Belagavi", "Hubli", "Dharwad", "Bengaluru", "Mysuru"])

print("\n2. City Column Added")
print(df)

# ----------------------------------------------------
# 3. Remove the Department column
# ----------------------------------------------------
df = df.drop("Department", axis=1)

print("\n3. Department Column Removed")
print(df)

# ----------------------------------------------------
# 4. Remove the employee with index 2
# ----------------------------------------------------
df = df.drop(2)

print("\n4. Employee at Index 2 Removed")
print(df)

# ----------------------------------------------------
# 5. Rename Salary to Monthly_Salary
# ----------------------------------------------------
df = df.rename(columns={"Salary": "Monthly_Salary"})

print("\n5. Salary Column Renamed")
print(df)

# ----------------------------------------------------
# 6. Rename Name to Employee_Name
# ----------------------------------------------------
df = df.rename(columns={"Name": "Employee_Name"})

print("\n6. Name Column Renamed")
print(df)

# ----------------------------------------------------
# 7. Add Bonus Column
# ----------------------------------------------------
df = df.assign(Bonus=[2000,3000,4000,2200])

print("\n7. Bonus Column Added")
print(df)

# ----------------------------------------------------
# 8. Create Total_Salary Column
# ----------------------------------------------------
df = df.assign(
    Total_Salary=df["Monthly_Salary"] + df["Bonus"]
)

print("\n8. Total Salary Column Added")
print(df)

# ----------------------------------------------------
# 9. Create Tax Column (10% of Salary)
# ----------------------------------------------------
df = df.assign(
    Tax=df["Monthly_Salary"] * 0.10
)

print("\n9. Tax Column Added")
print(df)

# ----------------------------------------------------
# 10. Final DataFrame
# ----------------------------------------------------
print("\n10. Final DataFrame")
print(df)

   Emp_ID   Name Department  Salary
0     101   Amit         HR   25000
1     102   Neha         IT   40000
2     103   Ravi    Finance   35000
3     104  Pooja         IT   50000
4     105  Karan         HR   28000

# Missing Values
# In real-world datasets, some values may be missing, empty, or unknown. These are called Missing Values and are represented as NaN (Not a Number) in Pandas.

In [109]:
import pandas as pd
import numpy as np

student = {
    "ID": [101, 102, 103, 104, 105],
    "Name": ["Rahul", "Anil", np.nan, "Sneha", "Kiran"],
    "Department": ["BCA", "BCA", "B.Sc", np.nan, "BCA"],
    "Marks": [85, np.nan, 78, 92, 80]
}

df = pd.DataFrame(student)

print(df)

    ID   Name Department  Marks
0  101  Rahul        BCA   85.0
1  102   Anil        BCA    NaN
2  103    NaN       B.Sc   78.0
3  104  Sneha        NaN   92.0
4  105  Kiran        BCA   80.0

In [110]:
# isnull()
# Returns True for missing values (NaN) and False for available values.

#Syntax
df.isnull()

      ID   Name  Department  Marks
0  False  False       False  False
1  False  False       False   True
2  False   True       False  False
3  False  False        True  False
4  False  False       False  False

In [111]:
print(df.isnull())

      ID   Name  Department  Marks
0  False  False       False  False
1  False  False       False   True
2  False   True       False  False
3  False  False        True  False
4  False  False       False  False

In [112]:
print(df.isnull().sum())

ID            0
Name          1
Department    1
Marks         1
dtype: int64

In [113]:
#notnull()
#Returns True for available values and False for missing values.

#Syntax
df.notnull()

     ID   Name  Department  Marks
0  True   True        True   True
1  True   True        True  False
2  True  False        True   True
3  True   True       False   True
4  True   True        True   True

In [114]:
print(df.notnull())

     ID   Name  Department  Marks
0  True   True        True   True
1  True   True        True  False
2  True  False        True   True
3  True   True       False   True
4  True   True        True   True

In [115]:
#Replace All Missing Values
print(df.fillna("Unknown"))

    ID     Name Department    Marks
0  101    Rahul        BCA     85.0
1  102     Anil        BCA  Unknown
2  103  Unknown       B.Sc     78.0
3  104    Sneha    Unknown     92.0
4  105    Kiran        BCA     80.0

In [116]:
#Replace Missing Marks with 0
df["Marks"] = df["Marks"].fillna(0)

print(df)

    ID   Name Department  Marks
0  101  Rahul        BCA   85.0
1  102   Anil        BCA    0.0
2  103    NaN       B.Sc   78.0
3  104  Sneha        NaN   92.0
4  105  Kiran        BCA   80.0

In [117]:
#Replace Missing Values with Mean
df["Marks"] = df["Marks"].fillna(df["Marks"].mean())

print(df)

    ID   Name Department  Marks
0  101  Rahul        BCA   85.0
1  102   Anil        BCA    0.0
2  103    NaN       B.Sc   78.0
3  104  Sneha        NaN   92.0
4  105  Kiran        BCA   80.0

In [ ]:
#dropna()
'''
Removes rows or columns containing missing values.

Syntax
df.dropna()
'''
#Remove Rows with Missing Values
print(df.dropna())

#Remove Columns with Missing Values
print(df.dropna(axis=1))

In [ ]:
Emp_ID	Name	Department	Salary
0	101	Amit	HR	25000.0
1	102	Neha	IT	NaN
2	103	NaN	Finance	35000.0
3	104	Pooja	NaN	50000.0
4	105	Karan	HR	28000.0
5	106	Ravi	Sales	NaN

Tasks
Display all missing values using isnull().
Count the missing values in each column.
Display all non-missing values using notnull().
Replace missing names with "Unknown".
Replace missing salaries with 0.
Replace missing salaries with the average salary.
Replace missing departments with "Not Assigned".
Remove all rows containing missing values.
Remove all columns containing missing values.
Remove only the rows where the Department column has missing values.

In [119]:
import pandas as pd
import numpy as np

# Create DataFrame
employee = {
    "Emp_ID": [101, 102, 103, 104, 105, 106],
    "Name": ["Amit", "Neha", np.nan, "Pooja", "Karan", "Ravi"],
    "Department": ["HR", "IT", "Finance", np.nan, "HR", "Sales"],
    "Salary": [25000, np.nan, 35000, 50000, 28000, np.nan]
}

df = pd.DataFrame(employee)

print("=" * 60)
print("ORIGINAL DATAFRAME")
print("=" * 60)
print(df)

# ----------------------------------------------------
# 1. Display missing values
# ----------------------------------------------------
print("\n1. Missing Values (isnull())")
print(df.isnull())

# ----------------------------------------------------
# 2. Count missing values
# ----------------------------------------------------
print("\n2. Count Missing Values")
print(df.isnull().sum())

# ----------------------------------------------------
# 3. Display non-missing values
# ----------------------------------------------------
print("\n3. Non-Missing Values (notnull())")
print(df.notnull())

# ----------------------------------------------------
# 4. Replace missing Name with 'Unknown'
# ----------------------------------------------------
df1 = df.copy()
df1["Name"] = df1["Name"].fillna("Unknown")

print("\n4. Replace Missing Name with 'Unknown'")
print(df1)

# ----------------------------------------------------
# 5. Replace missing Salary with 0
# ----------------------------------------------------
df2 = df.copy()
df2["Salary"] = df2["Salary"].fillna(0)

print("\n5. Replace Missing Salary with 0")
print(df2)

# ----------------------------------------------------
# 6. Replace missing Salary with Average Salary
# ----------------------------------------------------
df3 = df.copy()
df3["Salary"] = df3["Salary"].fillna(df3["Salary"].mean())

print("\n6. Replace Missing Salary with Average Salary")
print(df3)

# ----------------------------------------------------
# 7. Replace missing Department with 'Not Assigned'
# ----------------------------------------------------
df4 = df.copy()
df4["Department"] = df4["Department"].fillna("Not Assigned")

print("\n7. Replace Missing Department")
print(df4)

# ----------------------------------------------------
# 8. Remove rows with missing values
# ----------------------------------------------------
print("\n8. Remove Rows with Missing Values")
print(df.dropna())

# ----------------------------------------------------
# 9. Remove columns with missing values
# ----------------------------------------------------
print("\n9. Remove Columns with Missing Values")
print(df.dropna(axis=1))

# ----------------------------------------------------
# 10. Remove rows where Department is missing
# ----------------------------------------------------
print("\n10. Remove Rows with Missing Department")
print(df.dropna(subset=["Department"]))

print("\n" + "=" * 60)
print("PROGRAM COMPLETED SUCCESSFULLY")
print("=" * 60)

   Emp_ID   Name Department   Salary
0     101   Amit         HR  25000.0
1     102   Neha         IT      NaN
2     103    NaN    Finance  35000.0
3     104  Pooja        NaN  50000.0
4     105  Karan         HR  28000.0
5     106   Ravi      Sales      NaN

In [ ]:
#=================================================

# Value Analysis
# Value Analysis methods are used to analyze the values in a column. They help us find:

# How many times each value appears
# The unique values in a column
# The total number of unique values

In [ ]:
# value_counts()
# Returns the number of times each unique value appears in a column.
'''
Syntax
df["Column_Name"].value_counts()
'''

# Count Employees in Each Department
print(df["Department"].value_counts())

# Count Employees in Each City
print(df["City"].value_counts())

#===============================================
# unique()
Returns all unique values from a column.
'''
Syntax
df["Column_Name"].unique()
'''
#exa1
print(df["Department"].unique())

#exa2
print(df["City"].unique())

#=================================================
# nunique()
# Returns the total number of unique values in a column.
'''
Syntax
df["Column_Name"].nunique()
'''
#exa1
print(df["Department"].nunique())

#exa2
print(df["Department"].nunique())

#exa3
print(df["City"].nunique())

# Grouping Data
# The groupby() method is used to group rows that have the same value in one or more columns and then
# perform operations such as sum, mean, count, max, min, etc.

# It is commonly used to analyze grouped data, such as:

# Total salary by department
# Average marks by class
# Total sales by city
# Number of employees in each department

In [ ]:
# Syntax
df.groupby("Column_Name")

In [ ]:
# Group by Department
print(df.groupby("Department"))

In [ ]:
# Total Salary by Department
print(df.groupby("Department")["Salary"].sum())

In [ ]:
# Average Salary by Department
print(df.groupby("Department")["Salary"].mean())

In [ ]:
# Highest Salary by Department
print(df.groupby("Department")["Salary"].max())

In [ ]:
# Lowest Salary by Department
print(df.groupby("Department")["Salary"].min())

In [ ]:
# Employee Count by Department
print(df.groupby("Department")["Emp_ID"].count())

In [ ]:
# Group by City
print(df.groupby("City")["Salary"].sum())

In [ ]:
# Group by Multiple Columns
# Group by Department and City.

print(df.groupby(["Department", "City"])["Salary"].sum())

In [ ]:
# Multiple Calculations
print(df.groupby("Department")["Salary"].agg(["sum", "mean", "max", "min", "count"]))

# Combining DataFrames
# Sometimes data is stored in multiple DataFrames. Pandas provides methods to combine them into a single DataFrame.

In [ ]:
import pandas as pd

df1 = pd.DataFrame({
    "Emp_ID": [101, 102, 103],
    "Name": ["Amit", "Neha", "Ravi"]
})

df2 = pd.DataFrame({
    "Emp_ID": [104, 105, 106],
    "Name": ["Pooja", "Karan", "Meena"]
})

print("DataFrame 1")
print(df1)

print("\nDataFrame 2")
print(df2)

In [ ]:
#concat()
#Combines two or more DataFrames.
'''
Syntax
pd.concat([df1, df2])
'''

# Example 1: Vertical Concatenation
result = pd.concat([df1, df2])
print(result)


#Example 2: Horizontal Concatenation
df3 = pd.DataFrame({"Department": ["HR", "IT", "Finance"]})
result = pd.concat([df1, df3], axis=1)
print(result)


# merge()
'''
Combines DataFrames using a common column.
'''
# Sample Data
employee = pd.DataFrame({
    "Emp_ID": [101,102,103],
    "Name": ["Amit","Neha","Ravi"]
})

salary = pd.DataFrame({
    "Emp_ID": [101,102,103],
    "Salary": [25000,40000,35000]
})

#example
result = pd.merge(employee, salary, on="Emp_ID")
print(result)


# join()
'''
Joins DataFrames using their indexes.
'''
# Example
employee = pd.DataFrame({"Name": ["Amit", "Neha", "Ravi"]})
salary = pd.DataFrame({"Salary": [25000, 40000, 35000]})
result = employee.join(salary)
print(result)

# Saving Data
# After processing the data, we can save it into different file formats.

In [ ]:
import pandas as pd

employee = {
    "Emp_ID": [101,102,103],
    "Name": ["Amit","Neha","Ravi"],
    "Department": ["HR","IT","Finance"],
    "Salary": [25000,40000,35000]
}

df = pd.DataFrame(employee)

In [ ]:
# to_csv()
# Saves the DataFrame as a CSV file.
'''
Syntax
df.to_csv("employee.csv")
'''

#Example
df.to_csv("employee.csv", index=False)
print("CSV File Saved Successfully")

# to_excel()
#Saves the DataFrame as an Excel file.
'''
Syntax
df.to_excel("employee.xlsx")
'''
# Example
df.to_excel("employee.xlsx", index=False)
print("Excel File Saved Successfully")